[tool.poetry]
name = "dumpfun"
version = "0.1.0"
description = "Solana Paper Trading Platform"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.0"
uvicorn = "^0.15.0"
pydantic-settings = "^2.0.0"
aiohttp = "^3.8.1" 